### ISSUE TITLE
Using the downloaded weights doesn't create the expected result on the test data

### ISSUE THREAD

**Issue by sinapy** [ihdia/seamformer#1]
Hi. I'm loving the great documentation there is in this code. I was able to do everything as the steps provided

I'm attaching some of the outputs after doing
```
bash downloadWeights.sh
python ../inference.py --exp_name "sd_inf" --input_image_json 'data/SD/SD_Test/SD_TEST.json' --output_image_folder './sd_output' --model_weights_path '../weightsFolder/BKS.pt' 
``` 

I was hoping someone could help me with the issue I have with these outcomes

![vis_CB-3-18-90-7](https://github.com/ihdia/seamformer/assets/47465748/7aa46b0f-a8ad-4363-9e49-2958c65c169f)
![vis_CB-3-18-90-8](https://github.com/ihdia/seamformer/assets/47465748/5f1a367b-e6a5-44c1-8a61-485f12ad7b0e)
![vis_CB-3-18-90-9](https://github.com/ihdia/seamformer/assets/47465748/c3e5a25b-529e-4372-9cdd-681371d549d7)
![vis_CB-3-18-90-10](https://github.com/ihdia/seamformer/assets/47465748/451a8a1f-eb32-42e4-9c09-8e5fd9b8e331)
![vis_CB-3-18-90-12](https://github.com/ihdia/seamformer/assets/47465748/4cb7c805-2346-474d-9e83-6890581ccedd)
![vis_CB-3-22-90-14](https://github.com/ihdia/seamformer/assets/47465748/5bb4f579-9cc3-4081-b2a8-be490b4321fc)
![vis_CB-3-22-90-15](https://github.com/ihdia/seamformer/assets/47465748/fc346cc0-71c1-4459-b50a-ffeb71ef2281)

for example, look at the third segmented line of picture 1, and the third and fourth line of picture number 3

I'm running this on Windows 10, python version = 3.9

**Comment by hwaseem04** [comment]
Kindly do the inference now and feel free to reopen if you still face any issues. Thank you.
