### ISSUE TITLE
Error in Inference file:  Line no. 258 

### ISSUE THREAD

**Issue by dhirendracode** [ihdia/seamformer#3]
There is no need for **For Loop** while accessing image_path (line no.258) . You can access all key from data variable only.
I will pull the request and try to solve the error.
Thank you

**Comment by hwaseem04** [comment]
I believe you mean this line - `for i,record in enumerate(data):` in `Inference.py`

`data` is a list of file entries where each list item is a Dictionary.
`data = json.load(json_file)`

It need not just have a single image file information. So `for loop` is necessary. 

Feel free to reopen this issue if you are not convinced.

**Comment by dhirendracode** [comment]
Ok you are keeping common json for all images.
